spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration


jwt:
  secret: my_super_secret_key_for_jwt_1234567890
